#!/bin/sh

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#7aa2f7cc'
TEXT='#7aa2f7ee'
WRONG='#db4b4bee'
VERIFYING='#db4b4bee'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
--radius=120 \
--ring-width=15 \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 5                     \
--clock                      \
--indicator                  \
--time-str="%H:%M" \
--time-size=55 \
--date-size=55 \
--date-str="" \
--keylayout 0 \
\
--pass-media-keys \
--pass-screen-keys \
--pass-power-keys \
--pass-volume-keys \
