format = """
[](fg:blue)\
$directory\
[](fg:blue bg:cyan)\
$git_branch\
$git_status\
[ ](fg:cyan)\
"""

[directory]
style = "bg:blue fg:#24283b bold"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:cyan fg:#24283b bold"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:cyan fg:#24283b bold"
format = '[$all_status$ahead_behind ]($style)'
